version: "1.0"
tables:
  covid_tracking:
    file_path: "daily.csv"
    patient_id: null
    timestamp: "date"
    timestamp_format: "%Y%m%d"
    attributes:
      - "positive"
      - "probableCases"
      - "negative"
      - "pending"
      - "totalTestResultsSource"
      - "totalTestResults"
      - "hospitalizedCurrently"
      - "hospitalizedCumulative"
      - "inIcuCurrently"
      - "inIcuCumulative"
      - "onVentilatorCurrently"
      - "onVentilatorCumulative"
      - "recovered"
      - "lastUpdateEt"
      - "dateModified"
      - "checkTimeEt"
      - "death"
      - "hospitalized"
      - "hospitalizedDischarged"
      - "dateChecked"
      - "totalTestsViral"
      - "positiveTestsViral"
      - "negativeTestsViral"
      - "positiveCasesViral"
      - "deathConfirmed"
      - "deathProbable"
      - "totalTestEncountersViral"
      - "totalTestsPeopleViral"
      - "totalTestsAntibody"
      - "positiveTestsAntibody"
      - "negativeTestsAntibody"
      - "totalTestsPeopleAntibody"
      - "positiveTestsPeopleAntibody"
      - "negativeTestsPeopleAntibody"
      - "totalTestsPeopleAntigen"
      - "positiveTestsPeopleAntigen"
      - "totalTestsAntigen"
      - "positiveTestsAntigen"
      - "fips"
      - "positiveIncrease"
      - "negativeIncrease"
      - "total"
      - "totalTestResultsIncrease"
      - "posNeg"
      - "dataQualityGrade"
      - "deathIncrease"
      - "hospitalizedIncrease"
      - "hash"
      - "commercialScore"
      - "negativeRegularScore"
      - "negativeScore"
      - "positiveScore"
      - "score"
      - "grade"
